#ifndef MINIX_KERNEL_ARCH_EARM_BSP_INCLUDE_BSP_INIT_H_
#define MINIX_KERNEL_ARCH_EARM_BSP_INCLUDE_BSP_INIT_H_

/* BSP init */
void bsp_init(void);

#endif // MINIX_KERNEL_ARCH_EARM_BSP_INCLUDE_BSP_INIT_H_
